version: "3.7"

networks:
  lps-adapter-net:
    name: lps-adapter-net

services:
  lps-adapter:
    build:
      context: .
    container_name: lps-adapter
    command:
      - "sh"
      - "-c"
      - "sh /usr/wait-for/wait-for-mysql.sh && npm start"
    environment:
      DB_CONFIG: integration
      KNEX_CLIENT: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3308
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: testing
      REDIS_HOST: redis
      LOG_LEVEL: debug
      ADAPTOR_FSP_ID: adaptorRse
      # ACCOUNT_LOOKUP_URL: https://account-lookup-service.mojaloop.app
      # TRANSACTION_REQUESTS_URL: https://transaction-request-service.mojaloop.app
      # AUTHORIZATIONS_URL: https://transaction-request-service.mojaloop.app
      # QUOTE_REQUESTS_URL: https://quoting-service.mojaloop.app
      # TRANSFERS_URL: https://ml-api-adapter.mojaloop.app
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - lps-adapter-net
    depends_on:
      - mysql-mojaloop-adapter
      - redis-mojaloop-adapter
    volumes:
      - ./docker:/usr/wait-for
      - ./test:/usr/src/app/test
      - ./migrations:/usr/src/app/migrations
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:8000/health"]
      timeout: 20s
      retries: 10
      interval: 30s

  mysql-mojaloop-adapter:
    image: percona/percona-server:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    networks:
      - lps-adapter-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql-mojaloop-adapter"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  redis-mojaloop-adapter:
    image: redis
    container_name: redis-mojaloop-adapter
    environment:
      usePassword: "false"
    ports:
      - "6379:6379"
    networks:
      - lps-adapter-net
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s